### ISSUE TITLE
BeginGetAreaLocation caches the response even in case of failures.

### ISSUE THREAD

**Issue by omeshp** [Microsoft/azure-devops-node-api#187]
The code at https://github.com/Microsoft/vsts-node-api/blob/master/api/VsoClient.ts#L189 caches the response even in case of failures. So if a call like getBuild fails with timeout error, retrying the call fails with the same error.

**Comment by stephenmichaelf** [comment]
Will take a look, thanks!

**Comment by stephenmichaelf** [comment]
Is this resolved now? Can close if so.

**Comment by omeshp** [comment]
@stephenmichaelf The fix isn't ported to this repo, I have fixed it in "Download Build Artifacts" task, I can port it to this repo also. I have tested the changes for "Download Build Artifacts" scenario and they seems to be working fine.

**Comment by stephenmichaelf** [comment]
Doesn't your solution set the value to null? In the success case areaLocationsPromise has not been updated yet since the promise has not resolved.

**Comment by stephenmichaelf** [comment]
Also not sure why we have the node api copied into this Task? If there are changes needed in the node api we should make them there and reference as npm package.

**Comment by omeshp** [comment]
@stephenmichaelf No, the promise is assigned before hand, resolving the promise will just mark it fulfilled.

Regarding copying vso-node-api, there a set of pending issue which need to be fixed before we can use published version of vso-node-api, like the vso-node-api is currently using old typed-rest-client. Old typed-rest-client had issue with proxy and connection pooling because of which "Download Build Artifacts" task was failing for many customers.

**Comment by damccorm** [comment]
@omeshp, FYI we upgraded to the new typed-rest-client in #206. I'm adding a PR to port over your solution to this problem as well.
