### ISSUE TITLE
Profile Endpoint is failing

### ISSUE THREAD

**Issue by damccorm** [Microsoft/azure-devops-node-api#245]
Can't get profileApi from webApi. To reproduce, just try running samples, profile will fail.

Produces error:
> Error: Could not find information for resource area 8ccfef3d-2b87-4e99-8ccb-66e343d2daa8 ' + 'from server: https://dev.azure.com/damccorm

**Comment by damccorm** [comment]
@stephenmichaelf have you run into anything similar to this before? I did a little digging and as far as I can tell this is the correct endpoint. Also, is this reproducible for you? Could be an issue with my profile.

**Comment by damccorm** [comment]
I've narrowed the source of the issue down - calling getResourceAreas sends a request to {API_URL}/_apis/ResourceAreas, which is supposed to return all of the resource areas. It currently doesn't, however, contain the profile resource area. I'll go ahead and file a bug with the appropriate team.

**Comment by damccorm** [comment]
Looks like this has been resolved, must have been an issue on the backend that was fixed.

**Comment by nirendrashakya** [comment]
@damccorm It seems like the issue is still there in finding the profile Api. I get the same error message:
Error: Could not find information for resource area 8ccfef3d-2b87-4e99-8ccb-66e343d2daa8 ' + 'from server:

**Comment by desokey** [comment]
ran into the same issue, you have to use https://vssps.dev.azure.com/{org name}/ when calling getProfile method

**Comment by marc-wilson** [comment]
Getting the same error

**Comment by aarongriffin-snap** [comment]
+1 still breaking....
